#!/bin/bash

####INCOMPLETE
#NOTE FOR KEVIN: HOW TO DO I GET THIS TO READ A SITE BASED XML FILE (1 OF 6, e.g., CMH, CMP...) BASED ON CHARACTERS 5-8 IN SUBJECT ID?

####################################################################################
#Name:         05b_applyXML

#Last updated: 2020-04-26

#Description:  We want to run the DWI images through DTIprep, to clean them up
#              Creates the directory data/05b_dtiprepCleaned/

#Submission:   sbatch (remember to change the array to reflect number of participants)

#Notes:       ***THIS STEP MAY NOT BE NECESSARY -- REPLACED BY PROCESSING IN DMRIPREP***        
####################################################################################

#SBATCH --partition=moby
#SBATCH --array=1-475
#SBATCH --nodes=1
#SBATCH --time=20:00
#SBATCH --export=ALL
#SBATCH --job-name MRTRIX
#SBATCH --output=/projects/ncalarco/thesis/SPINS/Slicer/logs/run_%a.out
#SBATCH --error=/projects/ncalarco/thesis/SPINS/Slicer/logs/run_%a.err
#SBATCH --mem-per-cpu=1G

cd $SLURM_SUBMIT_DIR

subject_list="/projects/ncalarco/thesis/SPINS/Slicer/txt_outputs/03_sublist.txt"

index() {
   head -n $SLURM_ARRAY_TASK_ID $subject_list \
   | tail -n 1
}

#load modules 
module load DTIPrep/1.2.8

#define variables
inputdir='/projects/ncalarco/thesis/SPINS/Slicer/data/04_nrrd'
outputdir='/projects/ncalarco/thesis/SPINS/Slicer/data/05b_dtiprepCleaned'
dtiprep_protocols='/projects/ncalarco/thesis/SPINS/Slicer/data/05a_dtiprepProtocols'

#make directory
mkdir -p outputdir

#make the script tell us what participant it's on while it runs DTIPrep
echo `index`

if [ ! -e ${outdir}/`index`_QCed.nrrd ]; then
  DTIPrep \
    --DWINrrdFile ${inputdir}/`index`_eddy_fixed.nrrd \
    --xmlProtocol $dtiprep_protocol \
    --outputFolder ${outputdir} \
    --check 
else
    echo `index` "already has been DTIPrep-corrected"
fi
